#!/usr/bin/env bash

set -e
set -o pipefail

java_version=$(java -version 2>&1 | java -version 2>&1 | awk -F '"' '/version/ {print $2}')

# Export the keystore password for use in ws.conf
export KEY_PASSWORD=`cat scripts/password`

if [[ $java_version = 11* ]] ; then
    echo "The build is using Java 11 ($java_version). We need additional JVM parameters"
    export _JAVA_OPTIONS="$_JAVA_OPTIONS --add-modules=java.xml.bind"
else
    echo "The build is NOT using Java 11 ($java_version). No addional JVM params needed."
fi
